In [4]:
#Installing numpy
pip install numpy

SyntaxError: invalid syntax (641370216.py, line 2)

In [2]:
# Importing library numpy 

import numpy as np

In [4]:
Method 

a = np.array([1, 2, 3, 4, 5, 6])
print(a)

list = [100, 200, 300, 400]
b = np.array (list)
print(b)

[1 2 3 4 5 6]


In [6]:
array = np.arange(20)
print(array)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [7]:
x = np.arange(3, 10, 2)
print(x)

[3 5 7 9]
