In [15]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: C:\Users\apmle\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [16]:
import numpy as np


In [3]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

list = [100, 200, 300, 400]
b = np.array (list)
print(b)

[1 2 3 4 5 6]
[100 200 300 400]


In [6]:
x = np.arange(3, 10, 2)
print(x)

[3 5 7 9]


In [13]:
y = np.linspace(3, 10, 3)
print(y)

[ 3.   6.5 10. ]


In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [9]:
arr_zeros = np.zeros((3,5))
print(arr_zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
array2 = np.arange(20)
print(array2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [10]:
array = np.arange(20).reshape(4,5)
print(array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [11]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2) #The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
